import Head from "next/head";
import { Inter } from "next/font/google";
import StartBar from "../../components/StartBar/StartBar";
import "98.css"
import Win from "../../components/Win/Win"
import styles from "@/styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    return (
        <>
            <Head>
                <title>Shriya's Personal Website - Home Page</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Win title="Welcome!" width="500" body="to my website!" />
            </main>
            <StartBar />
        </>
    );
}