import Head from "next/head";
import { Inter } from "next/font/google";
import StartBar from "../../components/StartBar/StartBar";
import "98.css"
import styles from "@/styles/Home.module.css";
import DesktopIcon from "../../components/DesktopIcons/DesktopIcon";
import mycomp from "../../assets/mycomp.png";
import internet from "../../assets/internet.png";
import bin from "../../assets/recycling_bin.png";
import pdf from "../../assets/pdf.png";
import github from "../../assets/github.png";
import cmd from "../../assets/cmd.png";
import solitaire from "../../assets/solitaire.png";
import linkedin from "../../assets/linkedin.png";
import ErrorForm from "../../components/ErrorForm/ErrorForm";
import Win from "../../components/Win/Win";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const iconClicked = () => {
        console.log("Icon clicked");
    };

    const handleOpenGitHub = () => {
        window.open("https://github.com/shriyaasija", "_blank", "noreferrer");
    };

    const handleOpenLinkedin = () => {
        window.open("https://www.linkedin.com/in/shriya-asija/", "_blank", "noreferrer");
    };

    const handleOpenResume = () => {
        window.open("./resume.pdf");
    }

    return (
        <>
            <Head>
                <title>Shriya's Personal Website - Home Page</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <DesktopIcon id={1} doubleClick={iconClicked} title="My Comp" img={internet} />
                <DesktopIcon id={2} doubleClick={iconClicked} title="Recycling Bin" img={bin} />
                <DesktopIcon id={3} doubleClick={handleOpenResume} title="Resume" img={pdf} />
                <DesktopIcon id={4} doubleClick={handleOpenLinkedin} title="LinkedIn" img={linkedin} />
                <DesktopIcon id={5} doubleClick={handleOpenGitHub} title="GitHub" img={github} />
                <DesktopIcon id={6} doubleClick={iconClicked} title="Work" img={cmd} />
                <DesktopIcon id={7} doubleClick={iconClicked} title="Hobbies" img={solitaire} />
                <Win title={"Work"} width={"500"}>
                    hi
                </Win>
            </main>
            <StartBar />
        </>
    );
}